### ISSUE TITLE
Getting Error The file or directory to be published does not exist:

### ISSUE THREAD

**Issue by mhussain001** [lesha724/yii2-document-viewer#1]
Used following code to run sample
`<?php
echo \lesha724\documentviewer\ViewerJsDocumentViewer::widget([
   'url' => '/assets.xeo=id='>$files[0]['assets_id'], //url на ваш документ или http://example.com/test.odt
   'width'=>'100%',
   'height'=>'100%',
]);?>`

getting error

> Exception 'yii\base\InvalidParamException' with message 'The file or directory to be published does not exist: <ApplicationPATH>vendor/bower/viewerjs/ViewerJs' 

Can you please help

**Comment by lesha724** [comment]
Did you install fxp/composer-asset-plugin?

try
```
rm -rf ~/.composer/cache
rm -rf /path/to/project/vendor
rm /path/to/project/composer.lock
composer global require "fxp/composer-asset-plugin:1.4.2"
composer --prefer-dist install
```

**Comment by mhussain001** [comment]
Update to fxp/composer-asset-plugin v1.4.2

Still same issue.
ViewerJS exists in vendor/bower/viewerjs/

**Comment by lesha724** [comment]
Try update package to version v0.0.4

**Comment by mhussain001** [comment]
Thanks @lesha724 , it worked.
